# app/config/routing.yml

pipeline:
    resource: "@PipelineBundle/Controller/TrackerController.php"
    type:     annotation
    prefix:   /

# This simply removes any trailing slashes "/"
redirect:
    resource: "@PipelineBundle/Controller/RedirectController.php"
    type:     annotation
    prefix:   /

# Route all other URLs to a friendly error-message page
catchAll:
    resource: "@PipelineBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

# Anything listed below the catchAll route will never be called.
